#!/bin/bash

vercomp () {
  if [[ $1 == $2 ]]
  then
    return 0
  fi
  local IFS=.
  local i ver1=($1) ver2=($2)
  # fill empty fields in ver1 with zeros
  for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
  do
    ver1[i]=0
  done
  for ((i=0; i<${#ver1[@]}; i++))
  do
    if [[ -z ${ver2[i]} ]]
    then
      # fill empty fields in ver2 with zeros
      ver2[i]=0
    fi
    if ((10#${ver1[i]} > 10#${ver2[i]}))
    then
      return 1
    fi
    if ((10#${ver1[i]} < 10#${ver2[i]}))
    then
      return 2
    fi
  done
  return 0
}

# Build MongoDB image
if [[ $(docker images) == *jeffutter/mongodb* ]]
then
  MONGODB_VERSION=$(docker run --rm jeffutter/mongodb mongod --version | egrep -o '[[:digit:]\.]*'|head -n1)
  vercomp "$MONGODB_VERSION" '2.5.9999999999999999'                                                                                                                                                   
  if [[ $? == 1 ]]; then
    db_image="jeffutter/mongodb"
  else
    db_image="jeffutter/mongodb:2.4"
  fi
else 
  db_image="jeffutter/mongodb"
fi
docker pull "$db_image"

if [[ -f /etc/init/mongodb.conf ]]
then
  previous_mongo_install=true
else
  previous_mongo_install=false
fi
  
apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
echo deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen > /etc/apt/sources.list.d/10gen.list
apt-get update
apt-get -y install mongodb-clients

if [ $previous_mongo_install = false ]; then
  echo 'ENABLE_MONGODB="no"' > /etc/default/mongodb
fi

if [[ ! -d "$DOKKU_ROOT/.mongodb" ]]; then
  mkdir -p "$DOKKU_ROOT/.mongodb/data"

  admin_pass=$(openssl rand -base64 32|base64)
  echo $admin_pass > "$DOKKU_ROOT/.mongodb/admin_pw"

  chown -R dokku: "$DOKKU_ROOT/.mongodb"

  id=$(docker run -p 27017 -d -v "$DOKKU_ROOT/.mongodb/data":/tmp/mongo "$db_image" /usr/bin/mongod --dbpath=/tmp/mongo)
  mongodb_ip=$(docker port ${id} 27017 | awk '{split($0,a,":"); print a[1]}')
  mongodb_port=$(docker port ${id} 27017 | awk '{split($0,a,":"); print a[2]}')
  if [[ $mongodb_ip = "0.0.0.0" ]]; then
    mongodb_ip=127.0.0.1
  fi

  admin_success=false
  loop_count=0
  while [ $loop_count -lt 100 ];
  do
    echo "Connecting to server and creating admin user"
    sleep 2 # give mongodb some time to start
    create_output=$(mongo $mongodb_ip:$mongodb_port/admin --eval "db.createUser({user: \"admin\", pwd: \"${admin_pass}\", roles: [ \"root\" ]})")
    if [[ $? == 0 ]]; then
      echo "Admin user created successfully"
      admin_success=true
      break
    else
      echo $create_output
      loop_count=$((loop_count + 1))
    fi
  done
  docker stop "$id"

  if [ "$admin_sucess" = true ]; then
    echo "Unable to create the admin user!" 
  fi
fi

