#!/bin/bash
[[ $DOKKU_TRACE ]] && set -x

APP="$1"

#Old way of storing passwords
if [[ -f "$DOKKU_ROOT/.mongodb/pass_${APP}" ]]; then
  dokku mongodb:link $APP
fi


#new way supports multi db per db
shopt -s nullglob
set -- $DOKKU_ROOT/.mongodb/pass_${APP}_*
if [ "$#" -gt 0 ]; then
  for f in "$@"; do
    DATABASE=$( echo "$f" | cut -d'_' -f3 )
    dokku mongodb:link $APP $DATABASE
  done
fi
shopt -u nullglob